import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { LedgerTransaction } from './supabase';


export const generateLedgerReport = (roomName: string, transactions: LedgerTransaction[]) => {
  const formatDate = (dateString: string | Date | number) => {
    const d = new Date(dateString);
    const day = String(d.getDate()).padStart(2, '0');
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const year = d.getFullYear();
    return `${day}/${month}/${year}`;
  };

  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(44, 62, 80); // #2C3E50 Crisp deep charcoal-slate
  const title = roomName === 'Elite_Trip_Vault' ? 'Elite Trip Report' : `Abhiraj Dixit's Transactions`;
  doc.text(title, 14, 22);
  
  doc.setFontSize(12);
  doc.setTextColor(90, 108, 125);
  doc.text(`Room: ${roomName}`, 14, 30);
  doc.text(`Generated: ${formatDate(new Date())}`, 14, 36);

  // Grand Totals Calculation
  const totalDebit = transactions.filter(t => t.transaction_direction === 'outflow').reduce((sum, t) => sum + (t.amount_paisa / 100), 0);
  const totalCredit = transactions.filter(t => t.transaction_direction === 'inflow').reduce((sum, t) => sum + (t.amount_paisa / 100), 0);
  const totalDebitFormatted = totalDebit.toLocaleString('en-IN');
  const totalCreditFormatted = totalCredit.toLocaleString('en-IN');

  // Table Data
  const chronologicalTransactions = [...transactions].reverse();
  const tableData = chronologicalTransactions.map((item, index) => {
    let modeText = item.payment_method === 'online' ? 'Online' : 'Cash';
    const amountStr = (item.amount_paisa / 100).toLocaleString('en-IN');
    
    // Determine Debit vs Credit
    const debit = item.transaction_direction === 'outflow' ? amountStr : '-';
    const credit = item.transaction_direction === 'inflow' ? amountStr : '-';

    return [
      (index + 1).toString(),
      formatDate(item.created_at),
      modeText,
      item.category,
      item.description || 'N/A',
      debit,
      credit
    ];
  });

  autoTable(doc, {
    startY: 45,
    head: [['S.No', 'Date', 'Mode', 'Category', 'Description', 'Debit (Dr.)', 'Credit (Cr.)']],
    body: tableData,
    foot: [
      [
        { 
          content: 'GRAND TOTALS', 
          colSpan: 5, 
          styles: { halign: 'right', fontStyle: 'bold', fillColor: [30, 38, 56], textColor: 255 } 
        },
        { 
          content: totalDebitFormatted, 
          styles: { fontStyle: 'bold', fillColor: [244, 63, 94], textColor: 255 } // Crimson Red
        },
        { 
          content: totalCreditFormatted, 
          styles: { fontStyle: 'bold', fillColor: [16, 185, 129], textColor: 255 } // Emerald Green
        }
      ]
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [39, 174, 96], // #27AE60 Vibrant emerald-mint
      textColor: [255, 255, 255]
    },
    styles: {
      font: 'helvetica',
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: [244, 247, 246] // #F4F7F6 Ultra-light mint-ceramic white
    },
    didParseCell: function(data) {
      if (data.section === 'body') {
        const rawRow = data.row.raw as any[];
        const isHighlighted = rawRow && rawRow[4] && rawRow[4].toString().includes('[HIGHLIGHT]');
        if (isHighlighted) {
          data.cell.styles.fillColor = [254, 240, 138]; // #FEF08A Pale gold
          data.cell.styles.textColor = [0, 0, 0];
        }
        
        if (data.column.index === 4 && data.cell.text) {
          if (typeof data.cell.text === 'string') {
            (data.cell as any).text = (data.cell.text as string)
              .replace(/₹/g, 'Rs. ')
              .replace(/[^\x00-\x7F]/g, '')
              .replace(/\[HIGHLIGHT\]/g, '')
              .replace(/\[ELITE\]/g, '')
              .trim();
          } else if (Array.isArray(data.cell.text)) {
            (data.cell as any).text = (data.cell.text as string[]).map((t: string) => typeof t === 'string' ? t
              .replace(/₹/g, 'Rs. ')
              .replace(/[^\x00-\x7F]/g, '')
              .replace(/\[HIGHLIGHT\]/g, '')
              .replace(/\[ELITE\]/g, '')
              .trim() : t);
          }
        }
      }
    },
    didDrawPage: function (data) {
      const doc = data.doc;
      const str = 'Generated by RupeeMelt Core Engine V5.0';
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Muted slate color
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
    }
  });

  // --- Financial Summary Engine ---
  let totalCashbacks = 0;
  let totalOnlineExpenses = 0;
  let totalOfflineExpenses = 0;
  let grandTotalExpenses = 0;
  let totalInflow = 0;
  const expensesByCategory: Record<string, number> = {};

  transactions.forEach(t => {
    const amount = t.amount_paisa / 100;
    if (t.transaction_direction === 'inflow') {
      totalInflow += amount;
      if (t.category === 'Cashback') totalCashbacks += amount;
    } else if (t.transaction_direction === 'outflow') {
      grandTotalExpenses += amount;
      if (t.payment_method === 'online') totalOnlineExpenses += amount;
      if (t.payment_method === 'offline') totalOfflineExpenses += amount;
      expensesByCategory[t.category] = (expensesByCategory[t.category] || 0) + amount;
    }
  });

  const grandTotalMoneyLeft = totalInflow - grandTotalExpenses;

  const summaryData = [
    ['Total Cashbacks Received', `₹${totalCashbacks.toFixed(2)}`],
    ...Object.keys(expensesByCategory).map(cat => [`Expense Category: ${cat}`, `₹${expensesByCategory[cat].toFixed(2)}`]),
    ['Total Online Expenses', `₹${totalOnlineExpenses.toFixed(2)}`],
    ['Total Cash (Offline) Expenses', `₹${totalOfflineExpenses.toFixed(2)}`],
    ['Grand Total Expenses', `₹${grandTotalExpenses.toFixed(2)}`],
    ['Grand Total Money Left', `₹${grandTotalMoneyLeft.toFixed(2)}`]
  ];

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 15,
    head: [['Financial Summary Metrics', 'Amount']],
    body: summaryData,
    theme: 'grid',
    headStyles: {
      fillColor: [44, 62, 80],
      textColor: [255, 255, 255]
    },
    styles: {
      font: 'helvetica',
      fontSize: 11,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },
    didDrawPage: function (data) {
      const doc = data.doc;
      const str = 'Generated by RupeeMelt Core Engine V5.0';
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // Muted slate color
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
    }
  });

  const blobUrl = doc.output('bloburl');
  return {
    blobUrl: blobUrl.toString(),
    save: () => {
      doc.save(`RupeeMelt_${roomName.replace(/\s+/g, '_')}_Report.pdf`);
    }
  };
};
